# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mathew Ostrander
description: >
  Mathew Ostrander: Software Developer by day, Gamer by night, and Adventurer on the weekends. Mobile and Front-End Developer with Node.js training. Currently increasing Back-End capabilites by learning C#
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mathewostrander.com" # the base hostname & protocol for your site
twitter_username: OstranderMat
github_username:  MAOstrander

# Build settings
markdown: kramdown
