# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mathew Ostrander
description: >
  Mathew Ostrander: Full-time Full-Stack Developer, Full-time Father, Part time Game Master. I code as a career, delight in being a dad, and play games as a passion.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mathewostrander.com" # the base hostname & protocol for your site
twitter_username: OstranderMat
github_username:  MAOstrander

# Build settings
markdown: kramdown
